routes/web.php
<?php

use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\ClientController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TypeTasksController;
use App\Http\Controllers\UserController;
use App\Models\TaskType;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('home', '/tasks')->name('home');

Route::middleware('auth')->group(function () {
    Route::get('email/verify/{id}/{hash}', EmailVerificationController::class)
        ->middleware('signed')
        ->name('verification.verify');
    Route::post('logout', LogoutController::class)
        ->name('logout');

    Route::resource('tasks', TaskController::class);
    Route::get('/tasks', [TaskController::class, 'index'])->name('tasks.index');
    Route::post('/completed/{task}', [TaskController::class, 'completed'])->name('completed');
    Route::post('/notCompleted/{task}', [TaskController::class, 'notCompleted'])->name('notCompleted');
    Route::resource('clients', ClientController::class);
    Route::get('/clients', [ClientController::class, 'index'])->name('clients.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::get('/dashboard', [UserController::class, 'show'])->name('users.show');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description', 'expiration_date', 'user_id', 'completed', 'notCompleted', 'client_id', 'task_type_id', 'assigned_user_id'];


    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function client()
    {
        return $this->belongsTo(Client::class);
    }
    public function task_type()
    {
        return $this->hasOne(TaskType::class);
    }
}

app/Models/TaskType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TaskType extends Model
{
    use HasFactory;
    public function tasks()
    {
        return $this->belongsToMany(Task::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Task;
use App\Models\Client;
use App\Models\State;
use App\Models\TaskType;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tasks = Task::where('user_id', Auth::user()->id)->where('expiration_date', '>', date('Y-m-d'))->where('completed', '=', 0)->orderBy('name')->get();
        $expiredTasks = Task::where('user_id', Auth::user()->id)->where('expiration_date', '<',  date('Y-m-d'))->where('completed', '=',  0)->orderBy('name')->get();
        $completedTasks = Task::where('user_id', Auth::user()->id)->where('completed', '=',  1)->orderBy('name')->get();
        $types = TaskType::all();
        $clients = Client::all();
        $states = State::all();
        $users = User::all();
        return view('pages.tasks.index', [
            'tasks' => $tasks,
            'expiredTasks' => $expiredTasks,
            'completedTasks' => $completedTasks,
            'types' => $types,
            'clients' => $clients,
            'states' => $states,
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $types = TaskType::all();
        $clients = Client::all();
        $states = State::all();
        $users = User::all();
        return view('pages.tasks.create',
        [
            'types' => $types,
            'clients' => $clients,
            'states' => $states,
            'users' => $users,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $form_data = $request->all();
        $form_data['user_id'] = Auth::user()->id;
        $new_task = new Task();
        $new_task->fill($form_data);
        $new_task->completed = 0;
        $new_task->task_type_id = $form_data['task_type_id'];
        $new_task->client_id = $form_data['client_id'];
        $new_task->state_id = $form_data['state_id'];
        $new_task->assigned_user_id = $form_data['assigned_user_id'];
        $new_task->save();

        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Task $task)
    {
        $types = TaskType::all();
        $clients = Client::all();
        $states = State::all();
        $users = User::all();
        return view('pages.tasks.show', [
            'task' => $task,
            'types' => $types,
            'clients' => $clients,
            'states' => $states,
            'users' => $users,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Task $task)
    {

        $types = TaskType::all();
        $clients = Client::all();
        $states = State::all();
        $users = User::all();
        return view('pages.tasks.edit', [
            'task' => $task,
            'types' => $types,
            'clients' => $clients,
            'states' => $states,
            'users' => $users,
       ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Task $task)
    {
        $form_data = $request->all();
        $task->completed = 0;
        $task->update($form_data);
        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Task $task)
    {
       $task->delete();
       return redirect()->route('tasks.index')->with('message', "$task->name è stato eliminato");
    }

    public function completed(Request $request, Task $task)
    {
        $form_data = $request->all();
        $task->completed = 1;
        $task->update($form_data);
        return redirect()->back();
    }
    public function notCompleted(Request $request, Task $task)
    {
        $form_data = $request->all();
        $task->completed = 0;
        $task->update($form_data);
        return redirect()->route('tasks.index');
    }

}

resources/views/pages/tasks/create.blade.php
<?php
use function Laravel\Folio\{middleware};
//use function Livewire\Volt\{state};

middleware(['auth', 'verified']);
?>
<x-layouts.app>

<x-layouts.dashboard>

<form action="{{ route('tasks.store') }}" method="POST">
    @csrf
    <div class="relative z-0 w-full mb-6 group">
        <input type="text" name="name" id="name" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
        <label for="name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Type a name for your task</label>
    </div>
    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-6 group">
          <input type="text" name="description" id="description" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
          <label for="description" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Description</label>
      </div>
      <div class="relative z-0 w-full mb-6 group">
          <input type="date" name="expiration_date" id="expiration_date" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
          <label for="expiration_date" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Expiration Date</label>
      </div>
    </div>
    <div class="grid md:grid-cols-2 md:gap-6">

    </div>
    <div class="relative z-0 w-full mb-6 group">
       <select name="task_type_id" id="task_type_id" required>
           <option value="">Add a Type of task</option>
           @foreach ($types as $type)
        <option value="{{$type->id}}">{{$type->type}}</option>
        @endforeach
       </select>
       <select name="client_id" id="client_id" required>
           <option value="">Add a Client</option>
           @foreach ($clients as $client)
       <option value="{{$client->id}}">{{$client->name}}</option>
       @endforeach
      </select>
      <select name="state_id" id="state_id" required>
          <option value="">Add State </option>
          @foreach ($states as $state)
       <option value="{{$state->id}}">{{$state->state}}</option>
       @endforeach
      </select>
      <select name="assigned_user_id" id="assigned_user_id" required>
          <option value="">Add Operator</option>
          @foreach ($users as $user)
       <option value="{{$user->id}}">{{$user->name}}</option>
       @endforeach
      </select>
    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
</form>



</x-layouts.dashboard>

</x-layouts.app>

resources/views/pages/tasks/edit.blade.php
<?php
use function Laravel\Folio\{middleware};
//use function Livewire\Volt\{state};

middleware(['auth', 'verified']);
?>
<x-layouts.app>

<x-layouts.dashboard>


<form action="{{ route('tasks.update',$task->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="relative z-0 w-full mb-6 group">
        <input type="text" name="name" id="name" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required value="{{ old('name', $task->name) }}" />
        <label for="name" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Type a name for your task</label>
    </div>
    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-6 group">
          <input type="text" name="description" id="description" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required value="{{ old('description', $task->description) }}" />
          <label for="description" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Description</label>
      </div>
      <div class="relative z-0 w-full mb-6 group">
          <input type="date" name="expiration_date" id="expiration_date" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required value="{{ old('expiration_date', $task->expiration_date) }}"/>
          <label for="expiration_date" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Expiration Date</label>
      </div>
    </div>
    <div class="grid md:grid-cols-2 md:gap-6">
        <select name="task_type_id" id="task_type_id" required>
            @foreach ($types as $type)
           <option value="{{$type->id}}">{{$type->type}}</option>
           @endforeach
          </select>
          @if (Auth::user()->admin == 1)
          <select name="client_id" id="client_id" required>
            @foreach ($clients as $client)
           <option value="{{$client->id}}">{{$client->name}}</option>
           @endforeach
           @endif
          </select>
          @if (Auth::user()->admin == 1)
          <select name="assigned_user_id" id="assigned_user_id" required>
            @foreach ($users as $user)
           <option value="{{$user->id}}">{{$user->name}}</option>
           @endforeach
          </select>
          @endif
          <select name="state_id" id="state_id" required>
            <option value="">Add State </option>
            @foreach ($states as $state)
         <option value="{{$state->id}}">{{$state->state}}</option>
         @endforeach
        </select>
    </div>
    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
  </form>



</x-layouts.dashboard>

</x-layouts.app>

resources/views/pages/tasks/index.blade.php
<?php

use function Laravel\Folio\{middleware};
//use function Livewire\Volt\{state};

middleware(['auth', 'verified']);

?>

<x-layouts.dashboard>

<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        @media (max-width: 768px) {
            .flex-wrap {
                display: flex;
                flex-wrap: wrap;
            }
            .section-small {
                width: 50%;
            }
        }
    </style>
</head>
<body>
<div class="flex flex-col h-screen bg-gray-100">
    {{-- Main content --}}
    <div class="flex flex-1">

        <!-- Área de contenido principal -->
        <div class="flex-1 p-4">

            <!-- Contenedor de las 4 secciones (disminuido para dispositivos pequeños) -->
            <div class="grid grid-cols-1 gap-4 p-2 mt-2 md:grid-cols-2">
                <!-- Sección 1 - Gráfica de Usuarios (disminuida para dispositivos

                <!-- Sección 1 - Gráfica de Usuarios -->
                    <div class="p-4 bg-white rounded-md">
                        <h2 class="pb-1 text-lg font-semibold text-gray-500">Workflow</h2>
                        <div class="my1-"></div> <!-- Espacio de separación -->
                        <div class="h-px mb-6 bg-gradient-to-r from-cyan-300 to-cyan-500"></div> <!-- Línea con gradiente -->
                        <div class="chart-container" style="position: relative; height:150px; width:100%">
                            <!-- El canvas para la gráfica -->
                            <canvas id="usersChart"></canvas>
                        </div>
                    </div>

                    {{-- Expiration table --}}
                    <div class="p-4 bg-white rounded-md">
                        <h2 class="pb-4 text-lg font-semibold text-gray-500">Expired</h2>
                        <div class="my-1"></div>
                        <table class="w-full text-sm table-auto">
                            <thead>
                                <tr class="text-sm leading-normal">
                                    <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-light text-grey-light border-grey-light">Action</th>
                                    <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-ligh text-grey-light border-grey-light">Name</th>
                                    <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-light text-grey-light border-grey-light">description</th>
                                    <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-light text-grey-light border-grey-light">Expiration Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($expiredTasks as $Etask)
                                @if($Etask->completed == 0)
                                    <tr class="hover:bg-grey-lighter">

                                        <td class="px-4 py-2 text-blue-900 border-b border-grey-light"><a href="{{ route('tasks.show', $Etask->id) }}"><i class="fa-solid fa-eye"></i></a>
                                            <form method="POST" action="{{ route('completed', $Etask->id) }}">
                                                @csrf
                                                <button class="mt-4 text-green-900 completed-button" type="submit"><i class="fa-solid fa-check"></i></button>
                                            </form>
                                        </td>
                                    <td class="px-4 py-2 text-left border-b border-grey-light">{{$Etask->name}}</td>
                                    <td class="px-4 py-2 text-left border-b border-grey-light">{{$Etask->description}}</td>
                                    <td class="px-4 py-2 text-left border-b border-grey-light">{{$Etask->expiration_date}}</td>
                                 </tr>
                                 @endif
                                @endforeach

                            </tbody>
                            </table>
                    </div>

                    <!-- Sección 3 - Tabla de Autorizaciones Pendientes (disminuida para dispositivos pequeños) -->
            <div class="p-4 bg-white rounded-md">
                <h2 class="pb-4 text-lg font-semibold text-gray-500">Your Tasks</h2>
                <div class="my-1"></div> <!-- Espacio de separación -->
                <div class="h-px mb-6 bg-gradient-to-r from-cyan-300 to-cyan-500"></div> <!-- Línea con gradiente -->
                <table class="w-full text-sm table-auto">
                    <thead>
                        <tr class="text-sm leading-normal">
                            <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-light text-grey-light border-grey-light">Action</th>
                            <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-light text-grey-light border-grey-light">Name</th>
                            <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-light text-grey-light border-grey-light">description</th>
                            <th class="px-4 py-2 font-bold text-left uppercase border-b ptext-sm bg-grey-light text-grey-light border-grey-light">Expiration Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                        @if($task->completed == 0)
                            <tr class="hover:bg-grey-lighter">

                            <td class="px-4 py-2 text-blue-900 border-b border-grey-light"><a href="{{ route('tasks.show', $task->id) }}"><i class="fa-solid fa-eye"></i></a>
                                <form method="POST" action="{{ route('completed', $task->id) }}">
                                    @csrf
                                    <button class="mt-4 text-green-900 completed-button" type="submit"><i class="fa-solid fa-check"></i></button>
                                </form>
                            </td>
                            <td class="px-4 py-2 text-left border-b border-grey-light">{{$task->name}}</td>
                            <td class="px-4 py-2 text-left border-b border-grey-light">{{$task->description}}</td>
                            <td class="px-4 py-2 text-left border-b border-grey-light">{{$task->expiration_date}}</td>



                         </tr>
                         @endif
                        @endforeach

                    </tbody>
                    </table>
                    <div class="mt-4 text-right">
                        <a class="px-4 py-2 font-semibold text-white rounded bg-cyan-500 hover:bg-cyan-600" href="{{ route('tasks.create') }}">
                            Add A New Task
                        </a>
                    </div>
                </div>

                <!-- Sección 4 - Tabla de Transacciones (disminuida para dispositivos pequeños) -->
                     <div class="p-4 mt-4 bg-white rounded-md">
    <h2 class="pb-4 text-lg font-semibold text-gray-500">Tasks completed</h2>
    <div class="my-1"></div> <!-- Espacio de separación -->
    <div class="h-px mb-6 bg-gradient-to-r from-cyan-300 to-cyan-500"></div> <!-- Línea con gradiente -->
    <table class="w-full text-sm table-auto">
        <thead>
            <tr class="text-sm leading-normal">
                <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-lightest text-grey-light border-grey-light">Action</th>
                <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-lightest text-grey-light border-grey-light">Name</th>
                <th class="px-4 py-2 text-sm font-bold text-left uppercase border-b bg-grey-lightest text-grey-light border-grey-light">Description</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach($completedTasks as $Ctask)
                <tr class="hover:bg-grey-lighter">

                <td class="px-4 py-4 text-left text-blue-900 border-b border-grey-light"><a href="{{ route('tasks.show', $Ctask->id) }}"><i class="fa-solid fa-eye"></i></a></td>
                <td class="px-4 py-4 text-left border-b border-grey-light">{{$Ctask->name}}</td>
                <td class="px-4 py-4 text-left border-b border-grey-light">{{$Ctask->description}}</td>

             </tr>
            @endforeach

        </tbody>
    </table>
</div>


</div>
</div>
</div>


<!-- Script para las gráficas -->
<script>
    // Gráfica de Usuarios
    let usersChart = new Chart(document.getElementById('usersChart'), {
        type: 'doughnut',
        data: {
            labels: ['Active tasks', 'Expired tasks', 'Completed tasks'],
            datasets: [{
                data: [{{count($tasks)}}, {{count($expiredTasks)}}, {{count($completedTasks)}}],
                backgroundColor: ['#2b72cf', '#c93033', '#2bb32b'],
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            legend: {
                position: 'bottom' // Ubicar la leyenda debajo del círculo
            }
        }
    });

    // Gráfica de Comercios
    var commercesChart = new Chart(document.getElementById('commercesChart'), {
        type: 'doughnut',
        data: {
            labels: ['Nuevos', 'Registrados'],
            datasets: [{
                data: [60, 40],
                backgroundColor: ['#FEC500', '#8B8B8D'],
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            legend: {
                position: 'bottom' // Ubicar la leyenda debajo del círculo
            }
        }
    });

    // Agregar lógica para mostrar/ocultar la navegación lateral al hacer clic en el ícono de menú
    const menuBtn = document.getElementById('menuBtn');
    const sideNav = document.getElementById('sideNav');

    menuBtn.addEventListener('click', () => {
        sideNav.classList.toggle('hidden'); // Agrega o quita la clase 'hidden' para mostrar u ocultar la navegación lateral
    });
</script>
</body>
{{-- @volt('dashboard')
<div class="h-full py-12">
    <div class="h-full mx-auto max-w-7xl sm:px-6 lg:px-8">

        <div class="relative min-h-[500px] w-full h-full">
        </div>

    </div>
</div>
@endvolt --}}
</x-layouts.dashboard>

resources/views/pages/tasks/show.blade.php
<?php

use function Laravel\Folio\{middleware};
//use function Livewire\Volt\{state};

middleware(['auth', 'verified']);

?>

<x-layouts.dashboard>
<div class="container">
    <div class="title">
        <h2>{{$task->name}}</h2>
    </div>
    <div class="description">
        <p>{{$task->description}}</p>
    </div>
    <div class="date">
        <h3>{{$task->expiration_date}}</h3>
    </div>
    <div class="type">
        <h3>{{$types[$task->task_type_id -1]->type}}</h3>
    </div>
    <div class="client">
        <h3>{{$clients[$task->client_id -1]->name}}</h3>
    </div>
    <div class="operator">
        <h3>{{$users[$task->assigned_user_id -1]->name}}</h3>

    </div>
</div>
<div class="crud-buttons">

    <a href="{{ route('tasks.edit', $task->id) }}" class="px-4 py-2 font-semibold rounded text-dark bg-cyan-500 hover:bg-cyan-600">
        Edit Task
    </a>
    <form action="{{ route('tasks.destroy', $task->id) }}" method="POST">
        @method('DELETE')
        @csrf
        <div class="mt-5">
            <button type="submit" data-task-name="{{ $task->name }}" class="px-4 py-2 font-semibold bg-red-500 rounded text-dark hover:bg-red-600">
                Remove Task
            </button>
        </div>
    </form>
    <form method="POST" action="{{ route('notCompleted', $task->id) }}">
        @csrf
        {{-- <button class="text-dark-500 completed-button" type="submit">Not Completed Yet</button> --}}
        <button class="px-2 py-2 my-3 font-semibold bg-orange-500 rounded" type="submit">Not Completed Yet</button>

    </form>
</div>

</x-layouts.dashboard>